FROM node:14 as builder

WORKDIR /app/frontend
ENV PATH /app/frontend/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile --silent
RUN yarn global add react-scripts@4.0.3

COPY . ./
RUN yarn build

FROM nginx:stable
COPY --from=builder /app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;"]
