language: node_js

node_js:
  - 14

install: ./install-deps.sh

script:
  - node -v

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
