version: "3"

services:
  dms-back:
    container_name: dms-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 5676:5676
    volumes:
      - /app/backend/node_module

  dms-front:
    container_name: dms-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - /app/frontend/node_module
