version: "3"

services:
  ts-back:
    container_name: ts-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 5676:5676
    volumes:
      - /app/backend/node_module

  ts-front:
    container_name: ts-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 80:80
    volumes:
      - /app/frontend/node_module
