FROM node:16.0.0-buster-slim

WORKDIR /app/backend
ENV PATH /app/backend/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./

COPY . ./

RUN yarn

CMD [ "yarn", "start" ]
